# -*- coding: utf-8 -*-
"""Autocorrection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1heaErOJTyfdn3JT-0F21qAXOVClP3B0x
"""

!pip install ar-corrector

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('Final Output.csv', index_col=None)

df.head()

df.tail()

from ar_corrector.corrector import Corrector

corr = Corrector()

def auto_corr (df , col):
  for i in df.index :
    text=  df[col][i] 
    df[col][i]=corr.contextual_correct(text)

auto_corr(df , 'book_name')

auto_corr(df , 'book_category')

auto_corr(df , 'publisher')

df.head()

df.tail()

