# -*- coding: utf-8 -*-
"""IR Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XAE6QRTDKKdWoRm1agcyToi8yZXyLe7-
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import re
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv('IRModel.csv',encoding='utf-8')
df.head()

df.drop(['Unnamed: 0'], axis = 1, inplace=True)

df.head()

for i in df.index:
  df['author_name'][i] = re.sub(' +', ' ', df['author_name'][i])
  df['author_name'][i] = re.sub('^ +', '', df['author_name'][i])
  df['author_name'][i] = re.sub(' +$', '', df['author_name'][i])
  
  df['book_name'][i] = re.sub(' +', ' ', df['book_name'][i])
  df['book_name'][i] = re.sub('^ +', '', df['book_name'][i])
  df['book_name'][i] = re.sub(' +$', '', df['book_name'][i])
  
  df['book_category'][i] = re.sub(' +', ' ', df['book_category'][i])
  df['book_category'][i] = re.sub('^ +', '', df['book_category'][i])
  df['book_category'][i] = re.sub(' +$', '', df['book_category'][i])

#for i in df.index:
#    df['author_name'][i] = df['author_name'][i] + ' ' + df['book_name'][i] + ' ' + df['book_category'][i]

for i in range(0, 300):
  print(df['author_name'][i])

df.drop(['book_name'], axis = 1, inplace=True)
df.drop(['book_category'], axis = 1, inplace=True)

df.head()

df.tail()

df = df.rename(columns={'author_name': 'feature'})

df.head()

for i in df.index:
  if '0' in df['feature'][i]:
    df.drop(i, axis = 0, inplace=True)

df.drop(0, axis = 0, inplace=True)
df.drop(1, axis = 0, inplace=True)
df.drop(2, axis = 0, inplace=True)
df.drop(3, axis = 0, inplace=True)
df.drop(4, axis = 0, inplace=True)
df.drop(5, axis = 0, inplace=True)

df.reset_index(drop=True, inplace=True)

df.shape

df.head()

for i in range(0, 300):
  print(df['feature'][i])

df.head()

df.tail()

df.to_csv('IRModelFeatures.csv',encoding='utf-8')

q = ' يي أحمد خالد توفيق'

features = df['feature']
q = pd.Series(q)
features = pd.concat([features, q])
features.reset_index(drop=True, inplace=True)

vec_model = TfidfVectorizer()

features_vec=vec_model.fit_transform(features)
features_vec=pd.DataFrame.sparse.from_spmatrix(features_vec)


print(f'the new shape is{features_vec.shape}')

features.tail()

features_vec.head()

features[5520]

features_vec.shape

features_vec[5520]

features.shape

features[5520]

features_vec[5520]

features_vec.head()

lis = []
for i in features_vec.index:
  if i != 5416:
    lis.append(   ( float(cosine_similarity([features_vec[i]], [features_vec[5416]])), df['feature'][i])   )
lis = sorted(lis, reverse=True)

#for i in range(0, 11):
#  print(lis[i])

for i in range(0, 11):
  print(lis[i])

lis[-1]

float(cosine_similarity([[1,2,3,4,5]], [[0,5,4,0,0]]))

