# -*- coding: utf-8 -*-
"""KeywordExtraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmR5niFUBiq82h0Eg1uJaoiILTUOKsAS
"""

!pip install Arabic-Stopwords
! pip install yake
import yake
import arabicstopwords.arabicstopwords as stp

text = """أيا أيها السالك الطريق إلى الله، أيا أيها المحب المسترضى لربه أعلم كم أنت مشتاق لدخول الجنة وأعلم كم توجه من عقبات ومصاعب لذا أحببت أن تعينك بحول الله وقوته على جزء منها وأحببت أن أتشرف بصحبتك فى سيرك لاشرف غاية أحببت أن انبهك فتنتبه واذكرك فتتذكر أحببت ألا تفتى فتعيش شابا ولكن بقلب عجوز."""
words = text.split()
for word in words:
  if(stp.is_stop(word)):
    print(word + " => " + "True")
  else:
    words_list = words_list + " " + word
    print(word + " => " + "False")

print(words_list)

kw_extractor = yake.KeywordExtractor()
language = "ar"
max_ngram_size = 1
deduplication_threshold = 0.9
#numOfKeywords = 20
custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, features=None)
keywords = custom_kw_extractor.extract_keywords(words_list)
for kw in keywords:
  print(kw)